FROM ubuntu:trusty

RUN apt-get update && apt-get install -y nginx nginx-extras apache2-utils

VOLUME /media
VOLUME /var/www/journal
EXPOSE 80
EXPOSE 443
RUN rm /etc/nginx/sites-enabled/*

RUN mkdir -p /var/dav/temp
RUN useradd -ms /bin/bash test \
  && echo 'test:test' | chpasswd \
  && usermod -aG sudo test \
  && chown test:root -R /var/www/journal

